name: ServerLove
main: me.ratchetgame98.love.ServerLove
version: 2.0
description: >
             Server Love. Marry Date and Love your peers
commands:
  marry:
    description: Marry other players. Includes more arguments
  date:
    description: Date other players. Includes more arguments
  serverlove:
    description: Server Love admin commands and block requests
  inlove:
    description: Be in love with someone in the server <3
  kiss:
    descriptio: Kiss your partner <3